server {
    server_name dipenchauhan.com www.dipenchauhan.com;

    # Tell Nginx and Passenger where your app's 'public' directory is
    root /var/www/dipen_chauhan/code/public;

    # Max file size of uploads
    client_max_body_size 10M;

    # Turn on Passenger
    passenger_enabled on;
    passenger_ruby /home/deploy/.rvm/rubies/ruby-3.1.2/bin/ruby;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dipenchauhan.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dipenchauhan.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.dipenchauhan.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = dipenchauhan.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name dipenchauhan.com www.dipenchauhan.com;
    return 404; # managed by Certbot




}
